import test from 'node:test';
import assert from 'node:assert/strict';
import { initialConditions, DEFAULT_EXPERIMENT, WANDER_SHIFT, integrate, frameAt, diagnostics, createIntegration, createLiveComparison, STRIDE, MAX_FRAMES, separation } from '../threeBody/model.ts';
import { prepareComparison } from '../threeBody/runner.ts';
import { readState } from '../model.ts';
const defaults=()=>initialConditions(DEFAULT_EXPERIMENT);
test('published figure-eight starts with equal masses, zero momentum and angular momentum',()=>{const b=defaults(),d=diagnostics(b);assert.equal(b[2].vx,.93240737);assert.ok(Math.hypot(d.px,d.py,d.cx,d.cy,d.angular)<1e-12);});
test('20-time-unit figure-eight conserves energy, momentum, angular momentum and barycenter within declared tolerances',()=>{const t=integrate(defaults());assert.equal(t.reason,'complete');assert.equal(t.count,1001);assert.equal(t.values.byteLength,MAX_FRAMES*STRIDE*8);for(let i=0;i<t.count;i++){const f=frameAt(t,i);assert.ok(f[14]<1e-5);assert.ok(f[15]<1e-11);assert.ok(f[16]<1e-10);assert.ok(f[18]<1e-11);}assert.ok(Math.abs(frameAt(t,316)[0]-6.32)<1e-12);});
test('equal-mass triangle rotates preserving its three equal separations',()=>{const t=integrate(initialConditions({...DEFAULT_EXPERIMENT,preset:'triangle'}),{duration:4});assert.equal(t.reason,'complete');for(let i=0;i<t.count;i++){const f=frameAt(t,i),r=[];for(let j=0;j<3;j++){const k=(j+1)%3;r.push(Math.hypot(f[1+4*j]-f[1+4*k],f[2+4*j]-f[2+4*k]));}assert.ok(Math.max(...r)-Math.min(...r)<1e-10);assert.ok(Math.abs(r[0]-Math.sqrt(3))<1e-6);}});
test('curated wandering case is deterministic, separates visibly and runs past 70 time units',()=>{
  const triangle=initialConditions({...DEFAULT_EXPERIMENT,preset:'triangle'}),experiment={...DEFAULT_EXPERIMENT,preset:'wander'},initial=initialConditions(experiment);
  assert.deepEqual(initial.map(b=>b.mass),[1,1,1]);
  assert.ok(Math.abs((initial[2].x-initial[0].x)-(triangle[2].x-triangle[0].x)-WANDER_SHIFT.x)<1e-12);
  assert.ok(Math.abs((initial[2].vx-initial[0].vx)-(triangle[2].vx-triangle[0].vx)-WANDER_SHIFT.vx)<1e-12);
  const live=createLiveComparison(experiment);
  while(!live.done&&live.result.base.stopTime<40)live.advance(100);
  assert.equal(live.result.base.stopTime,40);
  const at40=frameAt(live.result.base,live.result.count-1).slice(),perturbed40=frameAt(live.result.perturbed,live.result.count-1);
  assert.ok(separation(at40,perturbed40)>3);
  const finer=createIntegration(initial,{step:.0005,continuous:true}),finerPerturbed=createIntegration(initialConditions(experiment,.0001),{step:.0005,continuous:true});
  while(!finer.done&&finer.trajectory.stopTime<40)finer.advance(1000);
  assert.equal(finer.trajectory.stopTime,40);
  assert.ok(separation(at40,frameAt(finer.trajectory,finer.trajectory.count-1))<.01);
  while(!live.done&&live.result.base.stopTime<70)live.advance(100);
  while(!finer.done&&finer.trajectory.stopTime<70)finer.advance(1000);
  while(!finerPerturbed.done&&finerPerturbed.trajectory.stopTime<70)finerPerturbed.advance(1000);
  assert.equal(live.done,false);assert.equal(finer.done,false);assert.equal(finerPerturbed.done,false);
  assert.equal(frameAt(live.result.base,live.result.count-1)[0],70);
  assert.equal(live.result.count,MAX_FRAMES);
  assert.ok(separation(frameAt(live.result.base,live.result.count-1),frameAt(live.result.perturbed,live.result.count-1))>1);
});
test('fixed-step solution converges at second order on a smooth interval',()=>{const a=integrate(defaults(),{step:.002,duration:2}),b=integrate(defaults(),{step:.001,duration:2}),c=integrate(defaults(),{step:.0005,duration:2});const ab=separation(frameAt(a,100),frameAt(b,100)),bc=separation(frameAt(b,100),frameAt(c,100));assert.ok(ab/bc>3.8&&ab/bc<4.2);});
test('scrubbing and different compute batches replay exactly the same stored states',()=>{const a=integrate(defaults(),{duration:2}),job=createIntegration(defaults(),{duration:2});while(!job.advance(17)){}assert.deepEqual(job.trajectory.values,a.values);const saved=Array.from(frameAt(a,42));frameAt(a,100);frameAt(a,0);assert.deepEqual(Array.from(frameAt(a,42)),saved);assert.deepEqual(integrate(defaults(),{duration:2}).values,a.values);});
test('close encounters stop at the last resolved sample without softening or crossing',()=>{const b=[{mass:1,x:-.01,y:0,vx:10,vy:0},{mass:1,x:.01,y:0,vx:-10,vy:0},{mass:1,x:1,y:0,vx:0,vy:0}];const t=integrate(b);assert.equal(t.reason,'close-encounter');assert.equal(t.count,1);assert.equal(t.stopTime,0);assert.ok([...t.values].every(Number.isFinite));const c=integrate([{...b[0],x:-.2},{...b[1],x:.2},b[2]]);assert.notEqual(c.reason,'complete');assert.ok(c.stopTime<.1);});
test('invalid physical parameters, time budgets and frame indices fail explicitly',()=>{for(const value of [NaN,Infinity,-1,0])assert.throws(()=>integrate([{...defaults()[0],mass:value},...defaults().slice(1)]),RangeError);assert.throws(()=>integrate(defaults(),{duration:21}),RangeError);assert.throws(()=>integrate(defaults(),{step:.00001}),RangeError);assert.throws(()=>initialConditions({...DEFAULT_EXPERIMENT,xC:NaN}),RangeError);assert.throws(()=>frameAt(integrate(defaults(),{duration:.02}),NaN),RangeError);});
test('modified third body is recentered without changing relative initial shifts',()=>{const a=initialConditions(DEFAULT_EXPERIMENT),b=initialConditions({...DEFAULT_EXPERIMENT,massC:1.5,xC:.1,vxC:.05}),d=diagnostics(b);assert.ok(Math.hypot(d.cx,d.cy,d.px,d.py)<1e-12);assert.ok(Math.abs((b[2].x-b[0].x)-(a[2].x-a[0].x)-.1)<1e-12);assert.equal(b[2].mass,1.5);});
test('inversion symmetry is preserved by pairwise forces and integration',()=>{const initial=defaults(),opposite=initial.map(b=>({...b,x:-b.x,y:-b.y,vx:-b.vx,vy:-b.vy})),a=integrate(initial,{duration:2}),b=integrate(opposite,{duration:2});for(let n=0;n<a.count;n++)for(let j=1;j<=12;j++)assert.equal(frameAt(a,n)[j],-frameAt(b,n)[j]);});
test('supported edited cases expose close-encounter and accuracy stops with only finite accepted frames',()=>{for(const [xC,reason] of [[.3,'close-encounter'],[-.3,'accuracy-limit']]){const t=integrate(initialConditions({...DEFAULT_EXPERIMENT,xC}));assert.equal(t.reason,reason);assert.ok(t.stopTime<20);for(let n=0;n<t.count;n++){const f=frameAt(t,n);assert.ok([...f].every(Number.isFinite));assert.ok(f[14]<=.001);assert.ok(f[17]>=.04);assert.ok(f[0]<=t.stopTime);}}});
test('numerical chapter route is explicit without changing the old orbit route',()=>{assert.equal(readState('?chapter=three-body').chapter,'three-body');assert.equal(readState('?chapter=orbits&system=triple').chapter,'orbits');assert.equal(readState('?chapter=sun').chapter,'sun');assert.equal(readState('?chapter=unknown').chapter,'evolution');});
test('async preparation rejects cancellation and allocates bounded matching deterministic histories',async()=>{const c=new AbortController();let yields=0;await assert.rejects(prepareComparison(DEFAULT_EXPERIMENT,c.signal,()=>{},async()=>{if(++yields===2)c.abort();}),{name:'AbortError'});assert.equal(yields,2);const result=await prepareComparison(DEFAULT_EXPERIMENT,new AbortController().signal,()=>{},async()=>{});assert.equal(result.count,1001);assert.equal(result.base.values.byteLength+result.perturbed.values.byteLength,304304);assert.ok(separation(frameAt(result.base,0),frameAt(result.perturbed,0))>0);});
