import { mountReadingMode } from '../../src/platform/readingMode.ts';
import { mountTopicNavigation } from '../../src/platform/topicNavigation.ts';
import { translateDocument } from '../../src/platform/i18n.ts';
import { t } from './i18n.ts';
import './style.css';
translateDocument(t);
mountTopicNavigation('water-states');
const el = (id: string) => document.getElementById(id)!;
const value = (id: string) => Number((el(id) as HTMLInputElement).value);
function update(){const kind=(el('process') as HTMLSelectElement).value,p=value('progress')/100,ice=kind==='melt'?1-p:kind==='freeze'?p:0;el('lid').setAttribute('display',kind==='condense'?'block':'none');el('invisible').setAttribute('display',kind==='evaporate'?'block':'none');const level=kind==='evaporate'?225+p*110:kind==='condense'?285:330-(1-ice)*115;el('water').setAttribute('display',ice>=.99?'none':'block');el('water').setAttribute('y',String(level));el('water').setAttribute('height',String(360-level));el('ice').innerHTML=Array.from({length:6},(_,i)=>{const size=61*ice;return `<g opacity="${ice}"><rect x="${345+(i%3)*68+(61-size)/2}" y="${215+Math.floor(i/3)*65+(61-size)/2}" width="${size}" height="${size}" rx="${Math.min(9,size/4)}" fill="#ccebf0" fill-opacity=".65" stroke="#65a6c2" stroke-width="2" transform="rotate(${i%2?5:-5} ${375+(i%3)*68} ${245+Math.floor(i/3)*65})"/><path d="M${350+(i%3)*68+(61-size)/2} ${220+Math.floor(i/3)*65+(61-size)/2}h${Math.max(0,size-12)}l${-size*.2} ${size*.18}h${-size*.55}Z" fill="#f6ffff" opacity=".65"/><path d="M${375+(i%3)*68} ${238+Math.floor(i/3)*65}l${-size*.08} ${size*.18} ${size*.13} ${size*.11}" fill="none" stroke="#f5ffff" stroke-width="1.3" opacity="${ice}"/></g>`;}).join('');el('droplets').innerHTML=Array.from({length:Math.floor(p*16)},(_,i)=>{const x=310+(i%8)*38,y=110+Math.floor(i/8)*29;return `<path d="M${x} ${y}q-10 15 0 16q10-1 0-16" fill="#70afc8"/>`;}).join('');el('environment').textContent=kind==='melt'?t('温暖的房间'):kind==='freeze'?t('冷冻室'):kind==='evaporate'?t('敞口的杯子'):t('冷盖子下方');el('state').textContent=kind==='condense'?t('冷盖子上出现小水滴'):kind==='evaporate'?t('水面降低，水进入空气'):ice>.98?t('固态：冰'):ice<.02?t('液态：水'):t('冰和水在一起');el('readout').textContent=kind==='melt'?t('冰在融化，液态水越来越多。'):kind==='freeze'?t('水在结冰；把环境变暖，还可以融化。'):kind==='evaporate'?t('水从表面慢慢进入空气。真正的水蒸气看不见，不是白色的云。'):t('空气里的水蒸气在冷盖子上凝结，变成看得见的小水滴。');}el('progress').addEventListener('input',update);function reset(){(el('progress') as HTMLInputElement).value='0';update();}el('process').addEventListener('change',reset);el('restart').addEventListener('click',reset);update();

mountReadingMode('details:not(.references)');
